exclude:
  - Gemfile

remote_theme: marella/jekyll-theme-documentation

title: WengerChan's Notes
toc_min: 2
toc_max: 3
owner_name: WengerChan
owner_url: https://github.com/WengerChan/notes

permalink: pretty
nav:
  - Getting Started:
    - About: ''
  - Docs:
    - Ansible: docs/Ansible
    - Awk: docs/Awk
    - Bonding: docs/Bonding
    - Emoji: docs/Emoji
    - Fedora-使用手册: docs/Fedora-使用手册
    - Git: docs/Git
    - Kvm: docs/Kvm
    - LVM: docs/LVM
    - Markdown: docs/Markdown
    - Netcat: docs/Netcat
    - Netfilter/iptables: docs/Netfilter-iptables
    - NFS: docs/NFS
    - NTP: docs/NTP
    - Shell: docs/Shell
    - Shell-多线程: docs/Shell-多线程
    - SSH: docs/SSH
    - Team: docs/Team
    - 双网卡路由: docs/双网卡路由
    - 正则表达式: docs/正则表达式
    - 证书: docs/证书
  - Drafts:
    - 计算机网络: drafts/计算机网络
    - 三次握手与四次挥手: drafts/三次握手与四次挥手
    - 左右mongodb右手redis读书笔记: drafts/左右mongodb右手redis读书笔记

