exclude:
  - Gemfile

remote_theme: marella/jekyll-theme-documentation

title: WengerChan's Notes
toc_min: 2
toc_max: 3
owner_name: WengerChan
owner_url: https://github.com/WengerChan/notes

permalink: pretty
nav:
  - Getting Started:
    - Content: ''
  - Docs:
    - Ansible: docs/Ansible
    - Bonding: docs/Bonding
    - Fedora-使用手册: docs/Fedora-使用手册
    - Git: docs/Git
    - Kvm: docs/Kvm
    - Netcat: docs/Netcat
    - Netfilter/iptables: docs/Netfilter-iptables
    - NFS: docs/NFS
    - Shell-多线程: docs/Shell-多线程
    - Team: docs/Team
    - 正则表达式: docs/正则表达式
  - Drafts:
    - 计算机网络: drafts/计算机网络
    - 三次握手与四次挥手: drafts/三次握手与四次挥手
    - 左右mongodb右手redis读书笔记: drafts/左右mongodb右手redis读书笔记

